### ISSUE TITLE
Demo not working on iphone IOS

### ISSUE THREAD

**Issue by frvillar** [KristofferStrube/Blazor.FileSystem#3]
'An unhandled error has occurred. Reload' message received
![IOSerror](https://github.com/KristofferStrube/Blazor.FileSystem/assets/22943435/9b809b25-e1e6-4cbe-8460-5750c8648cba)

**Comment by KristofferStrube** [comment]
You have to enable the File System API explicitly in certain version of iOS.
I'm leaving this open as it would be nice to have way to check whether it is supported like we have in some of my other wrappers.

**Comment by frvillar** [comment]
Same problem on Android Chome (BlueStacks on Win 10).
Searching how to...
Thanks

**Comment by frvillar** [comment]
From IOS console log (//inspect)
DEBUGmono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
ERRORcrit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The operation failed for an unknown transient reason (e.g. out of memory).
      
Microsoft.JSInterop.JSException: The operation failed for an unknown transient reason (e.g. out of memory).

   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at KristofferStrube.Blazor.FileSystem.StorageManagerService.GetOriginPrivateDirectoryAsync(FileSystemOptions options)
   at KristofferStrube.Blazor.FileSystem.StorageManagerService.GetOriginPrivateDirectoryAsync()
   at KristofferStrube.Blazor.FileSystem.WasmExample.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by KristofferStrube** [comment]
I will have to investigate this further. I haven't been able to replicate this myself yet but thanks for the stack trace. Is this the only demo page that break or do they all break? And does it break after some time or immediately when you load the page?

**Comment by frvillar** [comment]
Same error on MVP and File Explorer pages. 
Other pages ok

**Comment by frvillar** [comment]
In Search Mastodon page, using win 10 edge browser . received follwing warning in console
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.

**Comment by KristofferStrube** [comment]
Can you try to pull the repository down and run it locally?

**Comment by frvillar** [comment]
Yes, I will do that and will let you know later
